# # Generated by Django 3.2.13 on 2022-05-25 13:30

# import cloudinary.models
# from django.db import migrations, models
# import django.db.models.deletion


# class Migration(migrations.Migration):

#     dependencies = [
#         ('blog', '0003_alter_post_status'),
#     ]

#     operations = [
#         migrations.AddField(
#             model_name='post',
#             name='excerpt',
#             field=models.TextField(blank=True),
#         ),
#         migrations.AddField(
#             model_name='post',
#             name='featured_image',
#             field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
#         ),
#         migrations.CreateModel(
#             name='Comment',
#             fields=[
#                 ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
#                 ('name', models.CharField(max_length=80)),
#                 ('email', models.EmailField(max_length=254)),
#                 ('body', models.TextField()),
#                 ('created_on', models.DateTimeField(auto_now_add=True)),
#                 ('approved', models.BooleanField(default=False)),
#                 ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.post')),
#             ],
#             options={
#                 'ordering': ['created_on'],
#             },
#         ),
#     ]
